# Generated by Django 3.2.5 on 2021-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_sustainable',
            field=models.BooleanField(default=False),
        ),
    ]
